name: build-deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install dependencies
        run: yarn install
      - name: build for firebase
        run: npm run docs:src
        env:
          DEPLOYMENT_BASE: "/"
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: build for gh-pages
        run: npm run docs:src
        env:
          DEPLOYMENT_BASE: ${{format('/{0}/', github.event.repository.name)}}
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: src/.vuepress/dist
